### ISSUE TITLE
Cannot enable plugin (version from AssetLib)

### ISSUE THREAD

**Issue by smedelyan** [kubecz3k/FiniteStateMachine#25]
**Godot version:** 3.1 RC1
Try to download the plugin from the editor -> AssetLib, then try to activate it in Project Settings. You'll get an error that there's probably something wrong in FSMInit*** script. Is it maintained anymore?

**Comment by kubecz3k** [comment]
Hello, version in the store is made for 3.0. The plugin is maintained and will be maintained at least when it comes to ensuring it's working in new versions of Godot (our projects are using it). I'm very sorry for not updating it on time the port is almost done (we are using it in our projects already) as far as I remember there is only one issue when creating new states from inspector due to some engine changes in signals. If you want you can try it here:  https://www.dropbox.com/s/8v5xyicdk15p8cp/net.kivano.fsm.zip  (ensure you are using a control version system, or that you at least are testing it on a copy of your project).
I will fix remaining issues soon and update it asap

**Comment by smedelyan** [comment]
@kubecz3k thanks for the response
I think I'll wait until it is released for 3.1 then =)

**Comment by Kaligule** [comment]
@smedelyan Did you try it again? The plugin was updated for 3.1 in april and I can cofirm it is working fine.

**Comment by smedelyan** [comment]
@Kaligule sorry, didn't have an opportunity to try it.
If you say so then I'll close the issue, thanks!=)
